/**
 * @fileoverview gRPC-Web generated client stub for auth
 * @enhanceable
 * @public
 */

// Code generated by protoc-gen-grpc-web. DO NOT EDIT.
// versions:
// 	protoc-gen-grpc-web v1.5.0
// 	protoc              v3.20.3
// source: auth_service.proto


/* eslint-disable */
// @ts-nocheck



const grpc = {};
grpc.web = require('grpc-web');

const proto = {};
proto.auth = require('./auth_service_pb.js');

/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.auth.AuthServiceClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'text';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.auth.AuthServicePromiseClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'text';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.auth.RegisterUserRequest,
 *   !proto.auth.RegisterUserResponse>}
 */
const methodDescriptor_AuthService_RegisterUser = new grpc.web.MethodDescriptor(
  '/auth.AuthService/RegisterUser',
  grpc.web.MethodType.UNARY,
  proto.auth.RegisterUserRequest,
  proto.auth.RegisterUserResponse,
  /**
   * @param {!proto.auth.RegisterUserRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.auth.RegisterUserResponse.deserializeBinary
);


/**
 * @param {!proto.auth.RegisterUserRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.auth.RegisterUserResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.auth.RegisterUserResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.auth.AuthServiceClient.prototype.registerUser =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/auth.AuthService/RegisterUser',
      request,
      metadata || {},
      methodDescriptor_AuthService_RegisterUser,
      callback);
};


/**
 * @param {!proto.auth.RegisterUserRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.auth.RegisterUserResponse>}
 *     Promise that resolves to the response
 */
proto.auth.AuthServicePromiseClient.prototype.registerUser =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/auth.AuthService/RegisterUser',
      request,
      metadata || {},
      methodDescriptor_AuthService_RegisterUser);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.auth.AuthenticateUserRequest,
 *   !proto.auth.AuthenticateUserResponse>}
 */
const methodDescriptor_AuthService_AuthenticateUser = new grpc.web.MethodDescriptor(
  '/auth.AuthService/AuthenticateUser',
  grpc.web.MethodType.UNARY,
  proto.auth.AuthenticateUserRequest,
  proto.auth.AuthenticateUserResponse,
  /**
   * @param {!proto.auth.AuthenticateUserRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.auth.AuthenticateUserResponse.deserializeBinary
);


/**
 * @param {!proto.auth.AuthenticateUserRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.auth.AuthenticateUserResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.auth.AuthenticateUserResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.auth.AuthServiceClient.prototype.authenticateUser =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/auth.AuthService/AuthenticateUser',
      request,
      metadata || {},
      methodDescriptor_AuthService_AuthenticateUser,
      callback);
};


/**
 * @param {!proto.auth.AuthenticateUserRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.auth.AuthenticateUserResponse>}
 *     Promise that resolves to the response
 */
proto.auth.AuthServicePromiseClient.prototype.authenticateUser =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/auth.AuthService/AuthenticateUser',
      request,
      metadata || {},
      methodDescriptor_AuthService_AuthenticateUser);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.auth.GetUserDetailsRequest,
 *   !proto.auth.GetUserDetailsResponse>}
 */
const methodDescriptor_AuthService_GetUserDetails = new grpc.web.MethodDescriptor(
  '/auth.AuthService/GetUserDetails',
  grpc.web.MethodType.UNARY,
  proto.auth.GetUserDetailsRequest,
  proto.auth.GetUserDetailsResponse,
  /**
   * @param {!proto.auth.GetUserDetailsRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.auth.GetUserDetailsResponse.deserializeBinary
);


/**
 * @param {!proto.auth.GetUserDetailsRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.auth.GetUserDetailsResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.auth.GetUserDetailsResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.auth.AuthServiceClient.prototype.getUserDetails =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/auth.AuthService/GetUserDetails',
      request,
      metadata || {},
      methodDescriptor_AuthService_GetUserDetails,
      callback);
};


/**
 * @param {!proto.auth.GetUserDetailsRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.auth.GetUserDetailsResponse>}
 *     Promise that resolves to the response
 */
proto.auth.AuthServicePromiseClient.prototype.getUserDetails =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/auth.AuthService/GetUserDetails',
      request,
      metadata || {},
      methodDescriptor_AuthService_GetUserDetails);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.auth.VerifyTokenRequest,
 *   !proto.auth.VerifyTokenResponse>}
 */
const methodDescriptor_AuthService_VerifyToken = new grpc.web.MethodDescriptor(
  '/auth.AuthService/VerifyToken',
  grpc.web.MethodType.UNARY,
  proto.auth.VerifyTokenRequest,
  proto.auth.VerifyTokenResponse,
  /**
   * @param {!proto.auth.VerifyTokenRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.auth.VerifyTokenResponse.deserializeBinary
);


/**
 * @param {!proto.auth.VerifyTokenRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.auth.VerifyTokenResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.auth.VerifyTokenResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.auth.AuthServiceClient.prototype.verifyToken =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/auth.AuthService/VerifyToken',
      request,
      metadata || {},
      methodDescriptor_AuthService_VerifyToken,
      callback);
};


/**
 * @param {!proto.auth.VerifyTokenRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.auth.VerifyTokenResponse>}
 *     Promise that resolves to the response
 */
proto.auth.AuthServicePromiseClient.prototype.verifyToken =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/auth.AuthService/VerifyToken',
      request,
      metadata || {},
      methodDescriptor_AuthService_VerifyToken);
};


module.exports = proto.auth;

